name: Github actions test
on: [push]
jobs:
  Go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
      - run: go version
      - run: go build main.go
      - run: ./main

  First-Job:
    runs-on: ubuntu-latest
    steps:
      - run: pwd
      - run: whoami
      - run: sudo apt update
      - run: echo triggered by ${{ github.action }}
      - run: echo running os ${{ runner.os }}
      - run: echo branch ${{ github.ref }}
      - name: Checkout
        uses: actions/checkout@v2
      - run: ls
      - run: cd /
      - run: ls
      - run: echo repo ${{ github.repository }}
      - run: echo workspace ${{ github.workspace }}
      - name: list of files
        run: |
          ls ${{ github.workspace }}

  Second-Job:
    runs-on: ubuntu-latest
    steps:
      - run: ls
      - run: mkdir test
      - run: ls
      - run: cd test
      - run: ls -a